baseURL = "joy-yan.github.io/"
languageCode = "en-us"
title = "Hacking Number 42"
theme = "hugo-lodi-theme"
googleAnalytics = "UA-XXXXXXXX-Y"

[params]
    theme_color = "#574CDD"
    description = "Portfolio of Alexis Collado, UX Designer"
    description_photo = "img/profile.jpg"
    favicon = "favicon.png"
    logo = "logo.png"

    email = "joy.yan2016@gmail.com"
    wechat = "img/wechatQR.jpeg"
    linkedin = "https://www.linkedin.com/in/joyyan"
    github = "joy-yan"

[params.nav]
    enable = true

[params.hero]
    enable = true
    avatar = "profile.jpg"
    subtitle = "Hi! I'm Joy, an NLP Engineer, Game Designer, and Blogger."
    hero_right = ["<H1>Hacking Number 42</H1>",
                  "<p>Answer to the Ultimate Question of Life<p>",
                  "**Life Mottos**",
                  "* Progress and Service.",
                  "* Let the love of learning rule humanity.",
                  "* Head in the Clouds and Feet on the Ground.",
                  "**Currently**",
                  "* Implementing neo-huamnity application with AI, ARCore, ARKit, Android and iOS technologies.",
                  "* Pursung Master of Computer Science at Georgia Tech, Concentration: Machine Learning.",
                  "* Self studying complex systems and product design.",
                  "* Translating Tao Te Ching to English.",
                  "**Previously**",
                  "* BS. in Computer Science with honor at San Jose State University.",
                  "* NLP/ML Intern in Healthcare Startup in the Silicon Valley.",
                  "* PLM Application Developer at HD Solutions Germany.",
                  "* Research Intern at IBM Germany in NLP."
    ]
    resume = "JoyResume.pdf"


[params.process]
    enable = true
    title = "My Process"
    subtitle = "Design Thinking + System Thinking + Agile Management"

[params.case_studies]
    enable = true
    title = "Portfolio"
    subtitle = "Selected Works"

[params.footer]
    enable = true
